In [2]:
import pandas as pd

In [20]:
# Read the recent translated, combined responses csv file and sort by Matched
df = pd.read_csv("./random_test_data.csv").sort_values(by=['Matched'], ascending=False)

# Column names
colname_dict = {
    "Please enter your @canada.ca email.": "email",
    "What is your preferred name?": "name",
    "What language would you like to converse in?": "language",
    "When would you like to chat?": "time",
    "Which field are you in?": "field",
    "Do you want to be matched ONLY WITHIN your field?": "field_match",
    "What are your interests? Please list your interests separated by a comma with no spaces. I.e. cooking,drawing,etc.": "interests",
}

# Create a copy of df and remove all rows where Matched is Yes
dfCopy = df.copy().rename(colname_dict, axis=1).drop(df[df.Matched == "Yes"].index)

# Print dfCopy
display(dfCopy)

# Transform the dataframe into a list of dictionaries
records = dfCopy.to_dict('records')
total_records = len(records)

,email,name,language,time,field,field_match,interests,Matched
93,rebecca34@example.com,Eric Brown,French,No preference,8,No,"itself,people,nation,million,born,American,grow",No
160,smithjoseph@example.com,Mark Miranda,English,No preference,5,No,NaN,No
19,wvillanueva@example.com,Jenny Stafford,No preference,No preference,1,Yes,"choice,already,thank,source,she,light,question...",No
62,tbowman@example.com,Nicole Baker,No preference,Morning,9,Yes,"current,however,list,key,little,fast,speak,tre...",No
78,bfarrell@example.com,Tanya Walters,English,Afternoon,1,No,"blue,else,resource,part,instead,city,type,short",No
...,...,...,...,...,...,...,...,...
125,ycox@example.org,Kathleen Miller,French,No preference,9,Yes,"deep,walk,cause,trouble,movie,view,stuff,feder...",No
45,ernest37@example.com,Michael Clark,No preference,No preference,6,Yes,"mention,get,last,increase,mother",No
56,alvarezsandra@example.com,Timothy Fry,No preference,No preference,3,No,"manage,camera,beat,activity,stay",No
122,shawna10@example.org,Caleb Bell,English,Afternoon,8,Yes,"buy,many,partner,pressure,discover,carry,TV,dr...",No
68,chad65@example.org,Kristine Ward,No preference,No preference,1,No,"up,story,financial,state,hotel,matter,guy",No

In [21]:
# Function to test a pair
# If True, they match; otherwise False
def test_match(a, b):
    if a['language'] != b['language'] and "No preference" not in [a['language'], b['language']]:
        return False
    elif a['time'] != b['time'] and "No preference" not in [a['time'], b['time']]:
        return False
    elif a['field'] != b['field'] and "Yes" in [a['field_match'], b['field_match']]:
        return False
    else:
        a['Matched'] = "Yes"
        b['Matched'] = "Yes"
        return True

# Prepare lists to store matches and non-matches
match_successes = []
match_failures = []

# Main loop
while len(records) > 1:
    for i, n in enumerate(records):
        if i > 0:
            if test_match(records[0], n) is True:
                match_successes.append([records.pop(i), records.pop(0)])
                print(f"Match! records left: {len(records)}/{total_records}")
                break
        if i+1 == len(records):
            match_failures.append(records.pop(0))
            print("Cannot match a record...")

# Add the last record to the match failures
if len(records) > 0:
    match_failures.append(records.pop(0))

print(f"Matching complete!")
print(f"Number of matched records: {2*len(match_successes)}")
print(f"Number of unmatched records: {len(match_failures)}")

# Create a dataframe for non-matches and reverse the column naming
# This dataframe can be saved as a csv to be re-used later
unmatched_df = pd.DataFrame(match_failures).rename({v:k for k, v in colname_dict.items()}, axis=1)

Match! records left: 101/103
Match! records left: 99/103
Match! records left: 97/103
Match! records left: 95/103
Match! records left: 93/103
Match! records left: 91/103
Match! records left: 89/103
Match! records left: 87/103
Match! records left: 85/103
Match! records left: 83/103
Match! records left: 81/103
Match! records left: 79/103
Match! records left: 77/103
Match! records left: 75/103
Match! records left: 73/103
Match! records left: 71/103
Match! records left: 69/103
Match! records left: 67/103
Match! records left: 65/103
Match! records left: 63/103
Match! records left: 61/103
Match! records left: 59/103
Match! records left: 57/103
Match! records left: 55/103
Match! records left: 53/103
Match! records left: 51/103
Match! records left: 49/103
Match! records left: 47/103
Match! records left: 45/103
Match! records left: 43/103
Match! records left: 41/103
Match! records left: 39/103
Match! records left: 37/103
Match! records left: 35/103
Match! records left: 33/103
Match! records left: 31/103
Match! records left: 29/103
Match! records left: 27/103
Match! records left: 25/103
Match! records left: 23/103
Match! records left: 21/103
Match! records left: 19/103
Match! records left: 17/103
Match! records left: 15/103
Match! records left: 13/103
Match! records left: 11/103
Match! records left: 9/103
Match! records left: 7/103
Cannot match a record...
Cannot match a record...
Match! records left: 3/103
Match! records left: 1/103
Matching complete!
Number of matched records: 100
Number of unmatched records: 3

In [27]:
# Convert list to data frame and print
for i in range(len(match_successes)):
    match_successes[i] = pd.DataFrame(match_successes[i])
    display(match_successes[i])

,email,name,language,time,field,field_match,interests,Matched
0,qhernandez@example.org,Michael Adams,No preference,No preference,8,Yes,"wall,allow,power,condition,pressure,would,trut...",Yes
1,rebecca34@example.com,Eric Brown,French,No preference,8,No,"itself,people,nation,million,born,American,grow",Yes

,email,name,language,time,field,field_match,interests,Matched
0,bfarrell@example.com,Tanya Walters,English,Afternoon,1,No,"blue,else,resource,part,instead,city,type,short",Yes
1,smithjoseph@example.com,Mark Miranda,English,No preference,5,No,NaN,Yes

,email,name,language,time,field,field_match,interests,Matched
0,umiddleton@example.com,Diane Gordon DVM,French,Afternoon,1,No,"sign,executive,will,network,physical,play,pull...",Yes
1,wvillanueva@example.com,Jenny Stafford,No preference,No preference,1,Yes,"choice,already,thank,source,she,light,question...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,baileytonya@example.com,Hannah Anderson,No preference,Morning,9,Yes,"face,key,when,also,long,time,blood,bring,sprin...",Yes
1,tbowman@example.com,Nicole Baker,No preference,Morning,9,Yes,"current,however,list,key,little,fast,speak,tre...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,salazardiane@example.com,Andrew Perez,French,Afternoon,5,Yes,"agency,rich,accept,if,share,land,involve,educa...",Yes
1,mckinneyrebecca@example.org,Billy Page,No preference,Afternoon,5,Yes,amount,Yes

,email,name,language,time,field,field_match,interests,Matched
0,melissa97@example.net,Jonathan Hogan,English,Morning,7,Yes,"safe,street",Yes
1,shannon51@example.org,Janet Ortiz,English,Morning,7,No,"analysis,care,kitchen,purpose,difference,range...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,greenleroy@example.com,Matthew Moore,French,No preference,6,Yes,"white,maybe,read,card,look",Yes
1,zharris@example.org,Dawn Macias,No preference,Afternoon,6,Yes,NaN,Yes

,email,name,language,time,field,field_match,interests,Matched
0,qrobinson@example.com,Charles Melton,No preference,No preference,7,No,"take,one,them,in,decision,above,you,carry,poor...",Yes
1,jwerner@example.org,Jason Lawrence,No preference,Afternoon,5,No,"herself,population,seven",Yes

,email,name,language,time,field,field_match,interests,Matched
0,fwilson@example.org,Alex Drake,French,No preference,3,No,"tell,mention",Yes
1,dguzman@example.org,Morgan Hernandez,No preference,Afternoon,1,No,"herself,Mr,bad,wide,manage,address,information...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,hrobinson@example.org,Cindy Oconnor,No preference,No preference,8,Yes,"use,nice,themselves,gas,best,above,dinner,stuf...",Yes
1,greerdavid@example.org,Ryan Hoover,French,Morning,8,Yes,"whose,agreement",Yes

,email,name,language,time,field,field_match,interests,Matched
0,sheltonamy@example.com,Blake Pennington,French,No preference,1,Yes,everything,Yes
1,hbird@example.com,Jasmine Rowe,French,Afternoon,1,Yes,"within,though,finish,star,be,hot,often,worry,a...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,matthewmoreno@example.org,Jeffrey Ruiz,English,No preference,9,No,"leg,organization,nice,happy,international,sout...",Yes
1,scottcarroll@example.org,David Williams,English,Morning,5,No,"consider,staff,week,own,necessary,allow,includ...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,owensstephen@example.org,Steven Tran,English,No preference,9,Yes,"clear,newspaper,ball,may,read,information,fire...",Yes
1,djones@example.org,Lisa Ellis,No preference,Afternoon,9,Yes,"stuff,detail,himself,medical,fund,station,enou...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,samanthakramer@example.net,Jerome Manning,No preference,Afternoon,6,No,"without,prevent,ever,with,participant,form",Yes
1,millerjeffrey@example.net,Jordan Roman,No preference,Afternoon,3,No,"time,back,sound,city",Yes

,email,name,language,time,field,field_match,interests,Matched
0,jerome84@example.org,Krystal Hendricks,English,No preference,7,No,NaN,Yes
1,cruzcorey@example.com,Tony House,English,Morning,3,No,NaN,Yes

,email,name,language,time,field,field_match,interests,Matched
0,lloydvanessa@example.com,Olivia Gomez,No preference,No preference,3,No,"back,off,difficult,happen,high",Yes
1,rtran@example.com,Brian Whitaker,No preference,Afternoon,5,No,"yeah,simple,guess,member,hour,movement,time,be...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,lwright@example.net,Jesse Silva,French,No preference,7,No,NaN,Yes
1,aallen@example.net,Angie Chapman,French,Morning,9,No,"at,best,small,law,campaign,value",Yes

,email,name,language,time,field,field_match,interests,Matched
0,christopherallen@example.net,Michael Mendez,No preference,Morning,8,No,"three,doctor,nature,cup,whom,poor,send,through...",Yes
1,bsmith@example.com,Michael Sullivan,English,Morning,5,No,"beat,sometimes,Republican,agent,manage,special...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,katherinegibson@example.net,Harold Hayes,No preference,Afternoon,5,No,"look,call,spring,establish,together,record,sys...",Yes
1,carolyn24@example.org,Lori Lester,English,Afternoon,5,Yes,"serve,discuss,very,score,loss,they,grow,his,ca...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,kristinehiggins@example.com,Theresa Medina,English,Afternoon,8,Yes,"describe,method,meeting,space,military",Yes
1,jeffersonmark@example.com,Roy Fox,No preference,Afternoon,8,No,"matter,likely,prevent,hear",Yes

,email,name,language,time,field,field_match,interests,Matched
0,kristen09@example.com,Deanna Munoz,French,No preference,3,Yes,"woman,with,not,peace,put,maybe,main,fire,range...",Yes
1,lesliebowman@example.org,Jesus Smith,No preference,Morning,3,Yes,"trouble,it,grow,husband,short",Yes

,email,name,language,time,field,field_match,interests,Matched
0,bergmichael@example.net,Whitney Hess,English,Afternoon,7,Yes,"edge,couple,break,provide,drug,son,show,whatev...",Yes
1,uhansen@example.com,Ruth Castillo,English,Afternoon,7,No,"hair,look,too,reveal,safe,PM,too,right",Yes

,email,name,language,time,field,field_match,interests,Matched
0,bscott@example.org,Travis Hunt,No preference,No preference,3,No,"soldier,certain",Yes
1,matthewsalan@example.org,Jeffrey Ewing,English,Morning,6,No,"serious,successful,country",Yes

,email,name,language,time,field,field_match,interests,Matched
0,karla07@example.org,Michelle Maldonado,No preference,Morning,9,No,"speak,majority,large,but,hear,minute,discuss,s...",Yes
1,bradleyjohn@example.net,Anthony Johnson,French,Morning,9,Yes,"something,hair,do,analysis,him,above,bring,pai...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,audrey89@example.net,Michael Larson,French,Afternoon,5,Yes,"himself,with,garden,mention,economic,baby,book",Yes
1,timothywiggins@example.org,Michele Walls,French,No preference,5,Yes,"another,wonder,reveal,yet,possible,account",Yes

,email,name,language,time,field,field_match,interests,Matched
0,patrickmartin@example.net,Kevin Miller,No preference,Afternoon,1,No,"happy,far",Yes
1,qmiller@example.org,Nicholas Wright PhD,English,Afternoon,1,Yes,"fund,catch",Yes

,email,name,language,time,field,field_match,interests,Matched
0,tanya86@example.net,Victoria Hubbard,English,Morning,6,No,"professional,modern,north,good,program,risk,I,...",Yes
1,sarah14@example.com,Nicholas Barrett,No preference,Morning,7,No,"high,southern,job,high,she,past,especially,old...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,irivera@example.org,Theresa Edwards,English,No preference,6,Yes,north,Yes
1,jeffrey35@example.com,Victoria Manning,English,No preference,6,Yes,"realize,present,carry,break,majority,low,call,...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,alvarezsandra@example.com,Timothy Fry,No preference,No preference,3,No,"manage,camera,beat,activity,stay",Yes
1,amy83@example.net,Michael Torres,No preference,Afternoon,3,Yes,"war,resource,evening,realize,per,probably,her,...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,brucemcdonald@example.com,Lance King,French,Morning,8,Yes,NaN,Yes
1,vmartin@example.org,James Brewer,No preference,Morning,8,Yes,"table,scene,thing,responsibility,education,eve...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,perezbilly@example.org,Amanda Hebert,French,Afternoon,7,No,"available,despite,popular,stock,memory,challen...",Yes
1,flowe@example.org,Lindsay Archer,No preference,Afternoon,7,No,"collection,easy,would,federal,test,some,score,...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,sloanlauren@example.org,Dr. Robert Osborne,No preference,No preference,9,No,"bank,which,worker,second,late,every,include,ge...",Yes
1,simmonsashlee@example.net,Eric Price,English,Morning,9,Yes,"concern,attention,key,force,mention,general,te...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,christina51@example.net,Jimmy Moore,No preference,Morning,1,No,"former,run,others,believe,nor,after,small,stat...",Yes
1,vhale@example.org,Cheryl Gutierrez,No preference,Morning,1,No,"leave,institution,to,movie,seven",Yes

,email,name,language,time,field,field_match,interests,Matched
0,kristen30@example.net,Robert Miller,French,Afternoon,7,No,"that,admit,Mrs",Yes
1,davislori@example.net,Nicholas Smith,French,Afternoon,7,No,"much,why,design,need,assume,heart,west,trainin...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,isabelbanks@example.org,Peter Meyers,French,Morning,6,Yes,risk,Yes
1,williamssarah@example.com,Kayla Archer,No preference,Morning,6,Yes,"say,about,century,debate,officer,about,camera,...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,blairmatthew@example.net,Robin Harris,No preference,No preference,8,No,"deep,while,movie,tend,those,walk,draw,front,pl...",Yes
1,amymccarty@example.net,Paul Smith,English,Afternoon,6,No,"around,remember,take,ground,eat,determine,feel...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,richard47@example.com,Patricia Hudson,English,Morning,5,Yes,"speech,catch,ten,statement,carry,next,accordin...",Yes
1,jonesmichael@example.org,Megan Hart,English,Morning,5,Yes,"owner,ahead,generation,shoulder,day,popular,wi...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,kevin94@example.org,Amanda Peters,French,No preference,1,No,"raise,suggest,six,claim,analysis,school,moment...",Yes
1,fwaters@example.org,Matthew Bryant,French,Morning,9,No,"yet,so,before,wrong,take,old",Yes

,email,name,language,time,field,field_match,interests,Matched
0,alejandromccann@example.net,Jennifer Johnson,French,No preference,9,No,"line,page,structure,face,forget,result",Yes
1,fsmith@example.org,Kevin May,French,Afternoon,7,No,"work,several,past,next,final,tonight,table,los...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,tmartinez@example.org,Jeffrey Mcintyre,French,Afternoon,1,Yes,bill,Yes
1,josebryan@example.net,Lynn Herring,French,Afternoon,1,Yes,"trial,religious,your,outside,wish,community,ki...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,hendersondana@example.org,Bridget Thompson,No preference,Afternoon,7,No,"fast,drop,simply,or,century,their,defense,floo...",Yes
1,calhounsuzanne@example.net,Henry Winters,English,Afternoon,7,Yes,"moment,despite,before,under,between,candidate,...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,ernest37@example.com,Michael Clark,No preference,No preference,6,Yes,"mention,get,last,increase,mother",Yes
1,peter45@example.net,Morgan Johnson,French,Afternoon,6,Yes,choice,Yes

,email,name,language,time,field,field_match,interests,Matched
0,alexander69@example.net,Johnathan Long,No preference,No preference,5,Yes,"health,sort,couple,station,my,full,need,claim,...",Yes
1,mikerush@example.org,Margaret Sanchez,French,Afternoon,5,Yes,"resource,pretty,write,under,fear,knowledge,pla...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,andersonandrew@example.org,Lori Mitchell,English,No preference,7,No,"center,without,around,four,PM,hospital",Yes
1,natalie75@example.net,Jean Beard,English,Afternoon,8,No,"reflect,image,throughout,western,world,area,st...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,egarcia@example.org,Deborah Wong,English,No preference,1,No,"quickly,ok,road,military,west,practice,physica...",Yes
1,saunderskristina@example.org,Chris Young,English,Morning,1,Yes,"floor,role,agency,its,professor,while,seven,th...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,ycox@example.org,Kathleen Miller,French,No preference,9,Yes,"deep,walk,cause,trouble,movie,view,stuff,feder...",Yes
1,treid@example.com,John Gallegos,French,Morning,9,Yes,"camera,debate,western,store,office,explain,edu...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,robert02@example.com,Christine Knight,English,Afternoon,1,Yes,"all,structure,point,especially,that,product,fi...",Yes
1,forddana@example.com,Alexis Conrad,English,Afternoon,1,Yes,"government,support,improve,once,worry,newspape...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,ralphkelley@example.org,Rebecca Kirk,French,Afternoon,1,No,"learn,attention,cut,billion,eight",Yes
1,johnchavez@example.net,Shawn Taylor,French,Afternoon,5,No,"political,economic,seven,treatment,kid,reach",Yes

,email,name,language,time,field,field_match,interests,Matched
0,maria10@example.com,Lauren Parsons,French,No preference,8,No,NaN,Yes
1,fischerkelly@example.com,Kaitlin Johnson,No preference,Morning,8,Yes,"attack,evidence,especially,life,sister,officia...",Yes

,email,name,language,time,field,field_match,interests,Matched
0,chad65@example.org,Kristine Ward,No preference,No preference,1,No,"up,story,financial,state,hotel,matter,guy",Yes
1,gnash@example.org,Patrick Johnson,French,Afternoon,1,No,"along,particularly,factor,boy,Republican,without",Yes

In [31]:
# Install spacy and the the large english model
#!pip install spacy
#!python -m spacy download en_core_web_lg

Collecting en_core_web_lg==2.3.1
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-2.3.1/en_core_web_lg-2.3.1.tar.gz (782.7 MB)
     |███████████████████▊            | 483.1 MB 1.4 MB/s eta 0:03:29049.9 MB/s eta 0:00:04  | 418.4 MB 851 kB/s eta 0:07:08

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

     |███████████████████████████▌    | 672.3 MB 496 kB/s eta 0:03:43

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

     |████████████████████████████████| 782.7 MB 124.6 MB/s eta 0:00:01
Requirement already satisfied: spacy<2.4.0,>=2.3.0 in /opt/conda/lib/python3.8/site-packages (from en_core_web_lg==2.3.1) (2.3.5)
Requirement already satisfied: plac<1.2.0,>=0.9.6 in /opt/conda/lib/python3.8/site-packages (from spacy<2.4.0,>=2.3.0->en_core_web_lg==2.3.1) (1.1.3)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /opt/conda/lib/python3.8/site-packages (from spacy<2.4.0,>=2.3.0->en_core_web_lg==2.3.1) (4.51.0)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /opt/conda/lib/python3.8/site-packages (from spacy<2.4.0,>=2.3.0->en_core_web_lg==2.3.1) (2.0.5)
Requirement already satisfied: blis<0.8.0,>=0.4.0 in /opt/conda/lib/python3.8/site-packages (from spacy<2.4.0,>=2.3.0->en_core_web_lg==2.3.1) (0.7.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /opt/conda/lib/python3.8/site-packages (from spacy<2.4.0,>=2.3.0->en_core_web_lg==2.3.1) (2.22.0)
Requirement already satisfied: wasabi<1.1.0,>=0.4.0 in /opt/conda/lib/python3.8/site-packages (from spacy<2.4.0,>=2.3.0->en_core_web_lg==2.3.1) (0.8.0)
Requirement already satisfied: catalogue<1.1.0,>=0.0.7 in /opt/conda/lib/python3.8/site-packages (from spacy<2.4.0,>=2.3.0->en_core_web_lg==2.3.1) (1.0.0)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /opt/conda/lib/python3.8/site-packages (from spacy<2.4.0,>=2.3.0->en_core_web_lg==2.3.1) (3.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /opt/conda/lib/python3.8/site-packages (from spacy<2.4.0,>=2.3.0->en_core_web_lg==2.3.1) (1.0.5)
Requirement already satisfied: thinc<7.5.0,>=7.4.1 in /opt/conda/lib/python3.8/site-packages (from spacy<2.4.0,>=2.3.0->en_core_web_lg==2.3.1) (7.4.5)
Requirement already satisfied: srsly<1.1.0,>=1.0.2 in /opt/conda/lib/python3.8/site-packages (from spacy<2.4.0,>=2.3.0->en_core_web_lg==2.3.1) (1.0.5)
Requirement already satisfied: numpy>=1.15.0 in /opt/conda/lib/python3.8/site-packages (from spacy<2.4.0,>=2.3.0->en_core_web_lg==2.3.1) (1.19.4)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.8/site-packages (from spacy<2.4.0,>=2.3.0->en_core_web_lg==2.3.1) (49.6.0.post20201009)
Requirement already satisfied: idna<2.9,>=2.5 in /opt/conda/lib/python3.8/site-packages (from requests<3.0.0,>=2.13.0->spacy<2.4.0,>=2.3.0->en_core_web_lg==2.3.1) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/conda/lib/python3.8/site-packages (from requests<3.0.0,>=2.13.0->spacy<2.4.0,>=2.3.0->en_core_web_lg==2.3.1) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.8/site-packages (from requests<3.0.0,>=2.13.0->spacy<2.4.0,>=2.3.0->en_core_web_lg==2.3.1) (2020.12.5)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/conda/lib/python3.8/site-packages (from requests<3.0.0,>=2.13.0->spacy<2.4.0,>=2.3.0->en_core_web_lg==2.3.1) (3.0.4)
Building wheels for collected packages: en-core-web-lg
  Building wheel for en-core-web-lg (setup.py) ... done
  Created wheel for en-core-web-lg: filename=en_core_web_lg-2.3.1-py3-none-any.whl size=782936123 sha256=321d96811c7e4e0a2ef547f2dd3adf243baf44ed8e0d68d746f095737d542fb8
  Stored in directory: /tmp/pip-ephem-wheel-cache-wbffoiqf/wheels/8b/bb/bb/bdc918f4b37d930a1be9ed876e7b2c2ee518a34803d78a248e
Successfully built en-core-web-lg
Installing collected packages: en-core-web-lg
Successfully installed en-core-web-lg-2.3.1
✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_lg')

In [38]:
import spacy
import en_core_web_lg
nlp = en_core_web_lg.load()

In [42]:
# Check what type of object interests is
print(type(match_successes[1]['interests'][0]))
print(match_successes[1]['interests'][0])

<class 'str'>
blue,else,resource,part,instead,city,type,short

In [ ]:
# Function to find common interests
def common_interests(df):
    if df['interests'][0] == "NaN" and df['interests'][1] == "NaN":
        return "Both of you did not include your interests"
    elif df['interests'][0] == "NaN":
        return "Your common interests are: " + df['interests'][1]
    elif df['interests'][1] == "NaN":
        return "Your common interests are: " + df['interests'][0]
    else:
        # Split the string of interests by comma to create a list of interests
        i1 = df['interests'][0].split(",")
        i2 = df['interests'][1].split(",")

        # Lemmatize the words in both lists
        for i in range(len(i1)):
            i1[i] = nlp(i1[i].lemma_)

        for j in range(len(i2)):
            i2[j] = nlp(i2[j].lemma_)

        # Empty list to store common interests
        commonInterests = []

        # Find the simmilarity of all the words
        # from the shorter list compared to the longer list
        if len(i1 <= i2):
            for i in i1:
                for j in i2:
                    if (i1[i].similarity(i2.[j]) >= 0.9):
                        commonInterests.append(i1[i])
        else:
            for i in i2:
                for j in i1:
                    if (i2[i].similarity(i1.[j]) >= 0.9):
                        commonInterests.append(i2[i])

        return "Your common interests are: " + (', '.join(i) for i in commonInterests)